version: "3.8"

services:
  mitmproxy:
    build: mitmproxy
    ports:
      - "8002:8002"
    environment:
      - SERVER_HOSTNAME=secret_server
      - SERVER_PORT=8000
    depends_on:
      - secret_server

  secret_server:
    build: gunicornserver